[package]
name = "snowglobe-macros"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
proc-macro = true

[dependencies]
darling = "0.23"
humantime = "2"
proc-macro2 = "1"
quote = "1"
syn = "2"

[lints]
workspace = true
